# Generated by Django 2.1.7 on 2019-03-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_stock_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price (per kg)'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.FloatField(verbose_name='Quantity (in kg):'),
        ),
    ]
