# Generated by Django 2.1.7 on 2019-03-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_remove_stock_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tem_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customar_name', models.CharField(max_length=200)),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
