# Generated by Django 2.1.7 on 2019-03-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_tem_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customar_name', models.CharField(max_length=200)),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
